### ISSUE TITLE
[Launcher] add a start lan under the singleplayer button in the launcher

### ISSUE THREAD

**Issue by n00b7** [andrewphorn/ClassiCube-Client#321]
for people who have friends who want to play classicube at the same house this would be useful
once you click the button a tab would appear saying:
--------------------------------------------------------------------------
 lan game set on ip: (random ip) click ok to start
                                                                [ok]
---------------------------------------------------------------------------

then the server could be opened by using the direct connect button
type/paste the ip into the box and click
ok

and you will join the lan

(it would be a neat way to have a private server)

**Comment by fragmer** [comment]
It's possible to connect to local servers using the following syntax:

mc://123.45.67.89/username
(Implies using port 25565)

Or

mc://123.45.67.89:12345/username
(For non-standard ports)

**Comment by n00b7** [comment]
ok
