### ISSUE TITLE
(Suggestion) Re-sizing and or more human models.

### ISSUE THREAD

**Issue by sunburstflare** [andrewphorn/ClassiCube-Client#325]
Hi, Sun here. I've already discussed this with other people a few times, and I've gathered some information. I know by now that making model sizes any bigger than the current "giant" has collision issues, and that's understandable. But if possible, can anything be done for a size changing command, anything from 1/8 of your size, to x2? Just an idea, inspired by the Gulliver mod on minecraft premium. And if the whole size changing thing can't happen as a command, some new smaller or if possible bigger resizes would be very cewl.. Ex: "tiny" "micro" "small" I'm not _asking,_ by the way, just think it would be really awesome to see in the next update. I can also totally understand if too difficult to code. Thanks for reading, -Sun

**Comment by andrewphorn** [comment]
Classicube-client is no longer developed. This would be better suited as a
cpe extension, regardless.
